### ISSUE TITLE
Module details incomplete

### ISSUE THREAD

**Issue by Reshad-Rahman** [YangCatalog/search#19] opened 2018-11-04 04:21 UTC
https://www.yangcatalog.org/yang-search/module_details/module=iana-bfd-types@2018-08-01.yang?module=iana-bfd-types

Lots of good information there but there seems to be missing information, e.g.
1) Dependents and dependencies empty (dependents should be non-empty here)
2) When I click on yang-tree (https://yangcatalog.org/api/services/tree/iana-bfd-types@2018-08-01.yang) there's a server error
3) When I click on schema, I get 404 File not found

**Comment by miroslavKovacPantheon** [comment] 2018-11-06 10:54
Hi,

Indeed there was a problem. It should be fixed now. thank you

**Comment by Reshad-Rahman** [comment] 2018-11-08 03:28
Hi,

Thanks, the dependents/dependencies is fixed and the yang-tree also.
I still get 404 File not found when I click on the schema.

Regards,
Reshad.

**Comment by miroslavKovacPantheon** [comment] 2019-03-23 12:26
The 404 issue seemes to be fixed too.. The problem is with the older revision to which we have create another issue.
https://github.com/YangCatalog/backend/issues/64
I am closing this issue as it is resolved

**Closed by miroslavKovacPantheon** 2019-03-23 12:26 UTC
