### ISSUE TITLE
Some OpenDaylight YANG modules have been removed

### ISSUE THREAD

**Issue by bclaise** [YangCatalog/search#29] opened 2019-02-26 16:02 UTC
Hi,

https://www.yangcatalog.org/yang-searchhttps://www.yangcatalog.org/yang-search/?csrfmiddlewaretoken=6Vtk5mi4uythWar5gtyrrUqDAfLBPzU16ZHOiwmaI5lmmnb12cYWFnzXUiE5Y8H1&search_string=routing&onlyLatest=1&searchFields%5B%5D=module&searchFields%5B%5D=argument&yangVersions%5B%5D=1.0&yangVersions%5B%5D=1.1&headersAll=1&headersTypes%5B%5D=Name&headersTypes%5B%5D=Revision&headersTypes%5B%5D=Schema+Type&headersTypes%5B%5D=Path&headersTypes%5B%5D=Module&headersTypes%5B%5D=Origin&headersTypes%5B%5D=Organization&headersTypes%5B%5D=Maturity&headersTypes%5B%5D=Imported+By+%23+Modules&headersTypes%5B%5D=Compilation+Status&headersTypes%5B%5D=Description&submit=Search%21

This produces: 
ERROR! no opendaylight-sal-binding-broker-impl@2013-10-28 in API
ERROR! Search failed at opendaylight-sal-binding-broker-impl@2013-10-28/opendaylight: 'NoneType' object has no attribute 'get'

Recently some old OpenDaylight YANG modules have been removed from the YANG github.
This might the be reason.

Regards, Benoit

**Comment by miroslavKovacPantheon** [comment] 2019-02-26 16:15
Hi,


fixing the link here for others

https://www.yangcatalog.org/yang-search/?csrfmiddlewaretoken=6Vtk5mi4uythWar5gtyrrUqDAfLBPzU16ZHOiwmaI5lmmnb12cYWFnzXUiE5Y8H1&search_string=routing&onlyLatest=1&searchFields%5B%5D=module&searchFields%5B%5D=argument&yangVersions%5B%5D=1.0&yangVersions%5B%5D=1.1&headersAll=1&headersTypes%5B%5D=Name&headersTypes%5B%5D=Revision&headersTypes%5B%5D=Schema+Type&headersTypes%5B%5D=Path&headersTypes%5B%5D=Module&headersTypes%5B%5D=Origin&headersTypes%5B%5D=Organization&headersTypes%5B%5D=Maturity&headersTypes%5B%5D=Imported+By+%23+Modules&headersTypes%5B%5D=Compilation+Status&headersTypes%5B%5D=Description&submit=Search%21

@Benoit you had to copy paste https://www.yangcatalog.org/yang-search<https://www.yangcatalog.org/yang-search> twice by an accident.


Question how to solve this is wether we want to get rid of this module (which would be pretty easy) or do we rather want to get that module and its revision to yangcatalog. I don t know why it is missing but it s not one of the recently removed modules. I checked that. this is the only commit I found merged to odp recently.. -> https://github.com/YangModels/yang/commit/61aa90d29b102220565fcc98c26796e4c80a729e


Regards,

Miroslav Kovac

________________________________
Od: bclaise <notifications@github.com>
Odoslané: utorok, 26. februára 2019 17:02:12
Komu: YangCatalog/search
Kópia: Subscribed
Predmet: [YangCatalog/search] Some OpenDaylight YANG modules have been removed (#29)


Hi,

https://www.yangcatalog.org/yang-searchhttps://www.yangcatalog.org/yang-search/?csrfmiddlewaretoken=6Vtk5mi4uythWar5gtyrrUqDAfLBPzU16ZHOiwmaI5lmmnb12cYWFnzXUiE5Y8H1&search_string=routing&onlyLatest=1&searchFields%5B%5D=module&searchFields%5B%5D=argument&yangVersions%5B%5D=1.0&yangVersions%5B%5D=1.1&headersAll=1&headersTypes%5B%5D=Name&headersTypes%5B%5D=Revision&headersTypes%5B%5D=Schema+Type&headersTypes%5B%5D=Path&headersTypes%5B%5D=Module&headersTypes%5B%5D=Origin&headersTypes%5B%5D=Organization&headersTypes%5B%5D=Maturity&headersTypes%5B%5D=Imported+By+%23+Modules&headersTypes%5B%5D=Compilation+Status&headersTypes%5B%5D=Description&submit=Search%21

This produces:
ERROR! no opendaylight-sal-binding-broker-impl@2013-10-28 in API
ERROR! Search failed at opendaylight-sal-binding-broker-impl@2013-10-28/opendaylight: 'NoneType' object has no attribute 'get'

Recently some old OpenDaylight YANG modules have been removed from the YANG github.
This might the be reason.

Regards, Benoit

**Comment by SlavomirMazurPantheon** [comment] 2022-07-07 07:54
Hello,

I was unable to reproduce this error. In the meantime, we've improved our search engine, added notifications for users, and missing modules (and their dependencies) shouldn't cause problems at this time anymore.

I am closing this issue now - feel free to create new one if you identify similar issue.

Regards,
Slavomir Mazur

**Closed by SlavomirMazurPantheon** 2022-07-07 07:54 UTC
Labels: Priority: High, Maintenance
